CREATE DATABASE IF NOT EXISTS eShop;
USE eShop;

CREATE TABLE IF NOT EXISTS goods(
id INT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(70) NOT NULL,
price INT NOT NULL,
image VARCHAR(255) ,
amount INT NOT NULL,
discription TEXT,
update_date DATE NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `user`(
id INT NOT NULL AUTO_INCREMENT,
email VARCHAR(50) NOT NULL UNIQUE,
`password` VARCHAR(30) NOT NULL,
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS `role`(
id INT NOT NULL AUTO_INCREMENT,
`role` VARCHAR(50),
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS mark(
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
`value` INT(10) NOT NULL,
product_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (product_id) REFERENCES goods (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS user_role(
id INT NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
role_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (role_id) REFERENCES `role` (id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS tags(
id iNT NOT NULL AUTO_INCREMENT,
`name` VARCHAR(60) NOT NULL,
goods_id INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (goods_id) REFERENCES goods (id) ON DELETE CASCADE ON UPDATE CASCADE
);
